// ─────────────────────────────────────────────────────────────────────────────
// Mock Data — used as fallback when Supabase / external APIs aren't configured
// Every service file references these arrays so the app looks fully functional
// with zero env vars set.
// ─────────────────────────────────────────────────────────────────────────────

const now = () => new Date();
const daysAgo = (d) => new Date(Date.now() - d * 86400000).toISOString();
const hoursAgo = (h) => new Date(Date.now() - h * 3600000).toISOString();
const minsAgo = (m) => new Date(Date.now() - m * 60000).toISOString();
const daysAhead = (d) => new Date(Date.now() + d * 86400000).toISOString();

const MOCK_SUBSCRIBERS = [
  {
    id: 'sub_001',
    name: 'Marcus Johnson',
    email: 'marcus.johnson@example.com',
    phone: '+12025550101',
    tier: 'vip',
    status: 'active',
    subscribed_at: daysAgo(180),
    expires_at: daysAhead(185),
    last_call: hoursAgo(3),
    call_count: 31,
    notes: 'Real estate investor — 12 rental properties',
    created_at: daysAgo(180)
  },
  {
    id: 'sub_002',
    name: 'Sarah Chen',
    email: 'sarah.chen@example.com',
    phone: '+12025550102',
    tier: 'premium',
    status: 'active',
    subscribed_at: daysAgo(95),
    expires_at: daysAhead(270),
    last_call: hoursAgo(18),
    call_count: 14,
    notes: 'Tech consultant — considering S-Corp election',
    created_at: daysAgo(95)
  },
  {
    id: 'sub_003',
    name: 'David Ramirez',
    email: 'dramirez@example.com',
    phone: '+12025550103',
    tier: 'premium',
    status: 'active',
    subscribed_at: daysAgo(60),
    expires_at: daysAhead(305),
    last_call: daysAgo(2),
    call_count: 9,
    notes: 'E-commerce founder',
    created_at: daysAgo(60)
  },
  {
    id: 'sub_004',
    name: 'Priya Patel',
    email: 'priya.patel@example.com',
    phone: '+12025550104',
    tier: 'standard',
    status: 'active',
    subscribed_at: daysAgo(40),
    expires_at: daysAhead(325),
    last_call: daysAgo(1),
    call_count: 6,
    notes: 'W-2 employee exploring backdoor Roth',
    created_at: daysAgo(40)
  },
  {
    id: 'sub_005',
    name: 'James O\'Connor',
    email: 'jim.oconnor@example.com',
    phone: '+12025550105',
    tier: 'vip',
    status: 'active',
    subscribed_at: daysAgo(220),
    expires_at: daysAhead(145),
    last_call: hoursAgo(40),
    call_count: 22,
    notes: 'Retired — focus on RMDs & Roth conversions',
    created_at: daysAgo(220)
  },
  {
    id: 'sub_006',
    name: 'Aisha Williams',
    email: 'aisha.w@example.com',
    phone: '+12025550106',
    tier: 'standard',
    status: 'active',
    subscribed_at: daysAgo(25),
    expires_at: daysAhead(340),
    last_call: daysAgo(5),
    call_count: 3,
    notes: 'New subscriber — recent home purchase',
    created_at: daysAgo(25)
  },
  {
    id: 'sub_007',
    name: 'Robert Kim',
    email: 'rkim@example.com',
    phone: '+12025550107',
    tier: 'premium',
    status: 'expired',
    subscribed_at: daysAgo(400),
    expires_at: daysAgo(35),
    last_call: daysAgo(40),
    call_count: 11,
    notes: 'Let subscription lapse — reach out for renewal',
    created_at: daysAgo(400)
  },
  {
    id: 'sub_008',
    name: 'Elena Martinez',
    email: 'elena.m@example.com',
    phone: '+12025550108',
    tier: 'premium',
    status: 'active',
    subscribed_at: daysAgo(130),
    expires_at: daysAhead(235),
    last_call: hoursAgo(2),
    call_count: 18,
    notes: 'Short-term rental operator — 3 Airbnbs',
    created_at: daysAgo(130)
  }
];

const TRANSCRIPT_SCORP = [
  { role: 'agent',  at: '0:00', text: 'WBCPA Command Center — how can I help today?' },
  { role: 'caller', at: '0:04', text: 'Hi, this is Sarah Chen. I wanted to ask about doing an S-Corp election before year end.' },
  { role: 'agent',  at: '0:11', text: 'Got it Sarah — let me verify your account. One second.' },
  { role: 'agent',  at: '0:19', text: 'You\'re an active Premium subscriber. You mentioned year-end S-Corp — what\'s your projected net for 2024?' },
  { role: 'caller', at: '0:28', text: 'Around 240. So I\'m wondering if it\'s worth electing.' },
  { role: 'agent',  at: '0:34', text: 'At that income, it almost always pencils out. The break-even on payroll setup is roughly $80k of net. Quick math: if reasonable salary is $90k, you\'d save about $11k of self-employment tax annually, minus payroll filing costs of around $1,200.' },
  { role: 'caller', at: '0:51', text: 'Okay that\'s helpful. What\'s the timing?' },
  { role: 'agent',  at: '0:55', text: 'Form 2553 needs to go in by March 15 to be retroactive to January 1, 2025. If you want it to apply to 2024 retroactively, that\'s a late-election relief filing — possible but more complex.' },
  { role: 'caller', at: '1:12', text: 'Let\'s do 2025 then. Should I book a consult?' },
  { role: 'agent',  at: '1:16', text: 'Yes — I have Tuesday at 2pm or Thursday at 11am Eastern open. Which works?' },
  { role: 'caller', at: '1:24', text: 'Thursday 11.' },
  { role: 'agent',  at: '1:26', text: 'Booked. I\'ll text you the Google Meet link and a quick recap right after we hang up.' }
];

const TRANSCRIPT_1031 = [
  { role: 'agent',  at: '0:00', text: 'WBCPA Command Center.' },
  { role: 'caller', at: '0:02', text: 'Marcus Johnson. I\'m selling a rental — $1.1M sale, $680k basis. I need to defer the gains.' },
  { role: 'agent',  at: '0:11', text: 'Hi Marcus, you\'re looking at about $420k of gain. A 1031 exchange is the classic deferral here. Have you sold yet?' },
  { role: 'caller', at: '0:21', text: 'Closing in 9 days.' },
  { role: 'agent',  at: '0:23', text: 'Then we move fast. Two hard rules — 45 days from closing to identify replacement properties, 180 days to close on one. We need to wire proceeds to a Qualified Intermediary before closing — you cannot touch the funds.' },
  { role: 'caller', at: '0:38', text: 'Right. Do you guys have a QI you trust?' },
  { role: 'agent',  at: '0:41', text: 'Devon, our senior advisor, has two preferred firms. Let me book you a strategy session this week so he can walk you through replacement candidates and the timeline.' },
  { role: 'caller', at: '0:55', text: 'Yes please.' },
  { role: 'agent',  at: '0:56', text: 'Booking now — Wednesday at 10am Eastern, 45 minutes. Sending the meet link to your email and texting a recap.' }
];

const TRANSCRIPT_CP2000 = [
  { role: 'agent',  at: '0:00', text: 'WBCPA Command Center.' },
  { role: 'caller', at: '0:02', text: 'I just got a CP2000 — they say I owe $14,230. The 1099-Ks are double-counted, I think.' },
  { role: 'agent',  at: '0:13', text: 'That\'s a notice I want our human team to handle directly — IRS correspondence with potential audit exposure isn\'t something I close out alone. Let me transfer you to staff right now.' },
  { role: 'caller', at: '0:24', text: 'Okay, please.' },
  { role: 'agent',  at: '0:26', text: 'Transferring you to our staff line. While you wait — pull both the Stripe and PayPal 1099-K PDFs so we can reconcile on the call.' }
];

const MOCK_CALLS = [
  {
    id: 'call_001',
    bland_call_id: 'bl_a8f9c2',
    caller_number: '+12025550102',
    subscriber_id: 'sub_002',
    client_name: 'Sarah Chen',
    direction: 'inbound',
    duration_seconds: 512,
    summary: 'Client asked about S-Corp election timing before year-end. Discussed reasonable salary requirements and the payroll tax savings breakdown at her $240k net income. Recommended booking consultation to run exact numbers and file Form 2553.',
    topics_discussed: ['S-Corp election', 'Reasonable salary', 'Self-employment tax'],
    transcript: TRANSCRIPT_SCORP,
    action_needed: false,
    booking_made: true,
    transferred: false,
    recording_url: 'https://mock.bland.ai/recording/call_001.mp3',
    appointment_details: 'S-Corp consultation booked',
    sms_sent: true,
    called_at: hoursAgo(18)
  },
  {
    id: 'call_002',
    bland_call_id: 'bl_b3e721',
    caller_number: '+12025550101',
    subscriber_id: 'sub_001',
    client_name: 'Marcus Johnson',
    direction: 'inbound',
    duration_seconds: 687,
    summary: 'Client plans to sell a rental property ($680k basis, $1.1M sale price) and asked about deferring capital gains. Walked through 1031 exchange requirements, 45-day identification window, and qualified intermediary selection. Booked follow-up to review replacement property candidates.',
    topics_discussed: ['1031 exchange', 'Rental property', 'Capital gains deferral'],
    transcript: TRANSCRIPT_1031,
    action_needed: false,
    booking_made: true,
    transferred: false,
    recording_url: 'https://mock.bland.ai/recording/call_002.mp3',
    appointment_details: '1031 exchange strategy session',
    sms_sent: true,
    called_at: hoursAgo(3)
  },
  {
    id: 'call_003',
    bland_call_id: 'bl_c1d504',
    caller_number: '+12025550103',
    subscriber_id: 'sub_003',
    client_name: 'David Ramirez',
    direction: 'inbound',
    duration_seconds: 405,
    summary: 'Client received IRS CP2000 notice regarding underreported 1099-K income from payment processors. Transferred to human staff for immediate review — appears to be a duplicate reporting issue between Stripe and PayPal.',
    topics_discussed: ['IRS letter', 'CP2000 notice', '1099-K reconciliation'],
    transcript: TRANSCRIPT_CP2000,
    action_needed: true,
    booking_made: false,
    transferred: true,
    recording_url: 'https://mock.bland.ai/recording/call_003.mp3',
    appointment_details: null,
    sms_sent: true,
    called_at: daysAgo(2)
  },
  {
    id: 'call_004',
    bland_call_id: 'bl_d9e138',
    caller_number: '+12025550104',
    subscriber_id: 'sub_004',
    client_name: 'Priya Patel',
    direction: 'inbound',
    duration_seconds: 342,
    summary: 'W-2 employee at tech company with after-tax 401k option. Walked through mega backdoor Roth mechanics — $46,000 additional Roth capacity beyond the $23k employee deferral. Explained in-plan conversion vs in-service distribution. Client will confirm plan supports it and call back.',
    topics_discussed: ['Mega backdoor Roth', '401k', 'After-tax contributions'],
    action_needed: false,
    booking_made: false,
    transferred: false,
    recording_url: 'https://mock.bland.ai/recording/call_004.mp3',
    appointment_details: null,
    sms_sent: true,
    called_at: daysAgo(1)
  },
  {
    id: 'call_005',
    bland_call_id: 'bl_e7f942',
    caller_number: '+12025550106',
    subscriber_id: 'sub_006',
    client_name: 'Aisha Williams',
    direction: 'inbound',
    duration_seconds: 298,
    summary: 'New homeowner running a consulting side business from a home office. Covered Section 280A Augusta Rule (14 days of tax-free rental to own business), home office deduction calculation on 180 sqft dedicated space, and depreciation recapture on sale. Booked consultation to document properly.',
    topics_discussed: ['Home office deduction', 'Augusta Rule', 'Section 280A'],
    action_needed: false,
    booking_made: true,
    transferred: false,
    recording_url: 'https://mock.bland.ai/recording/call_005.mp3',
    appointment_details: 'Home office strategy consult',
    sms_sent: true,
    called_at: daysAgo(5)
  },
  {
    id: 'call_006',
    bland_call_id: 'bl_f2a683',
    caller_number: '+12025550108',
    subscriber_id: 'sub_008',
    client_name: 'Elena Martinez',
    direction: 'inbound',
    duration_seconds: 621,
    summary: 'Short-term rental operator asking about cost segregation on newly acquired Airbnb property ($720k purchase). Discussed bonus depreciation phase-down (60% in 2024), real estate professional status, and the material participation test for STRs under 7-day average rental. Recommended cost seg study and booked to review participation logs.',
    topics_discussed: ['Cost segregation', 'Bonus depreciation', 'STR rules', 'Material participation'],
    action_needed: false,
    booking_made: true,
    transferred: false,
    recording_url: 'https://mock.bland.ai/recording/call_006.mp3',
    appointment_details: 'Cost segregation review',
    sms_sent: true,
    called_at: hoursAgo(2)
  }
];

const MOCK_APPOINTMENTS = [
  {
    id: 'appt_001',
    subscriber_id: 'sub_002',
    call_log_id: 'call_001',
    client_name: 'Sarah Chen',
    client_email: 'sarah.chen@example.com',
    client_phone: '+12025550102',
    topic: 'S-Corp election consultation',
    scheduled_at: daysAhead(2),
    duration_min: 30,
    google_event_id: 'mock_gcal_001',
    meet_link: 'https://meet.google.com/mock-sarah-scorp',
    status: 'confirmed',
    notes: 'Review 2024 P&L before call',
    created_at: hoursAgo(18)
  },
  {
    id: 'appt_002',
    subscriber_id: 'sub_001',
    call_log_id: 'call_002',
    client_name: 'Marcus Johnson',
    client_email: 'marcus.johnson@example.com',
    client_phone: '+12025550101',
    topic: '1031 exchange strategy session',
    scheduled_at: daysAhead(3),
    duration_min: 45,
    google_event_id: 'mock_gcal_002',
    meet_link: 'https://meet.google.com/mock-marcus-1031',
    status: 'confirmed',
    notes: 'Bring replacement property shortlist',
    created_at: hoursAgo(3)
  },
  {
    id: 'appt_003',
    subscriber_id: 'sub_006',
    call_log_id: 'call_005',
    client_name: 'Aisha Williams',
    client_email: 'aisha.w@example.com',
    client_phone: '+12025550106',
    topic: 'Home office + Augusta Rule setup',
    scheduled_at: daysAhead(5),
    duration_min: 30,
    google_event_id: 'mock_gcal_003',
    meet_link: 'https://meet.google.com/mock-aisha-home',
    status: 'confirmed',
    notes: null,
    created_at: daysAgo(5)
  },
  {
    id: 'appt_004',
    subscriber_id: 'sub_008',
    call_log_id: 'call_006',
    client_name: 'Elena Martinez',
    client_email: 'elena.m@example.com',
    client_phone: '+12025550108',
    topic: 'Cost segregation study review',
    scheduled_at: daysAhead(7),
    duration_min: 45,
    google_event_id: 'mock_gcal_004',
    meet_link: 'https://meet.google.com/mock-elena-costseg',
    status: 'confirmed',
    notes: 'STR participation logs attached',
    created_at: hoursAgo(2)
  }
];

const MOCK_EMAILS = [
  {
    id: 'email_001',
    gmail_message_id: 'gm_001',
    subscriber_id: 'sub_002',
    client_name: 'Sarah Chen',
    client_email: 'sarah.chen@example.com',
    subject: 'Quick question about S-Corp salary',
    body: 'Hi team, following up on yesterday\'s call — for reasonable salary, is $90k a defensible number for a $240k net year as a tech consultant? Thanks!',
    received_at: hoursAgo(6),
    classification: 'question',
    urgency: 'low',
    needs_human: false,
    status: 'sent',
    ai_draft: 'Hi Sarah, a $90k salary on $240k net is generally defensible for a solo tech consultant based on BLS data for comparable W-2 roles...',
    sent_at: hoursAgo(5),
    season: 'PEAK_SEASON'
  },
  {
    id: 'email_002',
    gmail_message_id: 'gm_002',
    subscriber_id: 'sub_004',
    client_name: 'Priya Patel',
    client_email: 'priya.patel@example.com',
    subject: 'Backdoor Roth timing for 2024',
    body: 'Can I still do a backdoor Roth for 2024 if I contribute in February 2025? Want to make sure I don\'t miss the window.',
    received_at: hoursAgo(12),
    classification: 'question',
    urgency: 'medium',
    needs_human: false,
    status: 'sent',
    ai_draft: 'Hi Priya, yes — you have until the April 15 tax filing deadline to make 2024 IRA contributions...',
    sent_at: hoursAgo(11),
    season: 'PEAK_SEASON'
  },
  {
    id: 'email_003',
    gmail_message_id: 'gm_003',
    subscriber_id: 'sub_003',
    client_name: 'David Ramirez',
    client_email: 'dramirez@example.com',
    subject: 'IRS Notice CP2000 — received today',
    body: 'I got an IRS CP2000 notice claiming I owe $14,230 in additional tax. The 1099-K numbers look wrong — PayPal and Stripe both reported the same transactions. Urgent — please advise.',
    received_at: hoursAgo(4),
    classification: 'irs_notice',
    urgency: 'high',
    needs_human: true,
    status: 'review_needed',
    ai_draft: null,
    sent_at: null,
    season: 'PEAK_SEASON'
  },
  {
    id: 'email_004',
    gmail_message_id: 'gm_004',
    subscriber_id: 'sub_001',
    client_name: 'Marcus Johnson',
    client_email: 'marcus.johnson@example.com',
    subject: 'Documents for 1031 exchange',
    body: 'What docs should I bring Thursday? Settlement statements? Appraisals? Just want to be ready.',
    received_at: minsAgo(45),
    classification: 'logistics',
    urgency: 'low',
    needs_human: false,
    status: 'pending',
    ai_draft: null,
    sent_at: null,
    season: 'PEAK_SEASON'
  }
];

const MOCK_REVIEW_QUEUE = [
  {
    id: 'rq_001',
    type: 'email',
    source: 'email_agent',
    email_log_id: 'email_003',
    call_log_id: null,
    client_name: 'David Ramirez',
    client_phone: '+12025550103',
    client_email: 'dramirez@example.com',
    subject: 'IRS Notice CP2000 — received today',
    reason_flagged: 'IRS correspondence requires human review before response. Potential audit exposure.',
    urgency: 'high',
    status: 'open',
    claimed_by_id: null,
    claimed_by_name: null,
    claimed_at: null,
    resolved_by_id: null,
    resolved_by_name: null,
    resolved_at: null,
    resolution_notes: null,
    ai_handoff_summary: 'Caller reported a CP2000 notice claiming $14,230 in additional tax. Initial transcript review shows duplicate reporting between Stripe and PayPal of ~$82k in 1099-K transactions. Client is anxious — recommended immediate human follow-up.',
    created_at: hoursAgo(4)
  },
  {
    id: 'rq_002',
    type: 'call',
    source: 'bland_agent',
    email_log_id: null,
    call_log_id: 'call_003',
    client_name: 'David Ramirez',
    client_phone: '+12025550103',
    client_email: 'dramirez@example.com',
    subject: 'Amended return likely needed — duplicate 1099-K reporting',
    reason_flagged: 'Complex amended return situation — involves coordination with two payment processors.',
    urgency: 'high',
    status: 'claimed',
    claimed_by_id: 'tm_003',
    claimed_by_name: 'Devon Parker',
    claimed_at: hoursAgo(1),
    resolved_by_id: null,
    resolved_by_name: null,
    resolved_at: null,
    resolution_notes: null,
    ai_handoff_summary: 'On-call escalation. Caller pressed 0 mid-conversation when AI explained 1099-K reconciliation steps. Transcript shows client clearly wanted human help. Transferred at 03:42 mark.',
    created_at: daysAgo(2)
  },
  {
    id: 'rq_003',
    type: 'call',
    source: 'bland_agent',
    email_log_id: null,
    call_log_id: null,
    client_name: 'Unknown caller',
    client_phone: '+14155558821',
    client_email: null,
    subject: 'Unverified caller — wants to discuss back-taxes',
    reason_flagged: 'Phone number does not match any active subscription. Caller mentioned back-tax issues spanning 3 years.',
    urgency: 'medium',
    status: 'open',
    claimed_by_id: null,
    claimed_by_name: null,
    claimed_at: null,
    resolved_by_id: null,
    resolved_by_name: null,
    resolved_at: null,
    resolution_notes: null,
    ai_handoff_summary: 'Caller from +1 (415) 555-8821 said they have unfiled returns from 2021–2023 and are receiving collection letters. Not in subscriber DB. AI ended call politely with intake form link, but caller seemed in distress — flagged for outreach.',
    created_at: minsAgo(38)
  },
  {
    id: 'rq_004',
    type: 'email',
    source: 'email_agent',
    email_log_id: null,
    call_log_id: null,
    client_name: 'Sarah Chen',
    client_phone: '+12025550102',
    client_email: 'sarah.chen@example.com',
    subject: 'Re: S-Corp election — has changed her mind',
    reason_flagged: 'Client requested AI cancel her booked S-Corp consultation. Sentiment dropped — recommend personal call before processing cancellation.',
    urgency: 'medium',
    status: 'open',
    claimed_by_id: null,
    claimed_by_name: null,
    claimed_at: null,
    resolved_by_id: null,
    resolved_by_name: null,
    resolved_at: null,
    resolution_notes: null,
    ai_handoff_summary: 'Sarah replied to her appointment confirmation saying "actually I think I will skip this — too much hassle". This contradicts her clear interest from the original call. Worth a quick human check-in to see if it\'s a misunderstanding.',
    created_at: hoursAgo(2)
  },
  {
    id: 'rq_005',
    type: 'call',
    source: 'bland_agent',
    email_log_id: null,
    call_log_id: null,
    client_name: 'Marcus Johnson',
    client_phone: '+12025550101',
    client_email: 'marcus.johnson@example.com',
    subject: 'Resolved — already followed up',
    reason_flagged: 'Caller wanted to confirm wire instructions for QI on 1031 exchange.',
    urgency: 'low',
    status: 'resolved',
    claimed_by_id: 'tm_005',
    claimed_by_name: 'Luis Ortega',
    claimed_at: daysAgo(1),
    resolved_by_id: 'tm_005',
    resolved_by_name: 'Luis Ortega',
    resolved_at: hoursAgo(20),
    resolution_notes: 'Confirmed wire instructions over the phone with Marcus and emailed a copy. He is good to go.',
    ai_handoff_summary: 'Marcus called wanting to confirm wire details for his QI. Verification info matches. AI recommended human verbal confirmation given the financial sensitivity.',
    created_at: daysAgo(1)
  }
];

const MOCK_CONFIG = {
  current_season: 'PEAK_SEASON',
  voice_agent_enabled: true,
  auto_send_enabled: true,
  agent_name: 'WBCPA Command Center'
};

const MOCK_CLIENTS = [
  {
    id: 'cli_001',
    name: 'Marcus Johnson',
    email: 'marcus.johnson@example.com',
    entity_type: 'S-Corp',
    next_deadline: daysAhead(9),
    next_deadline_type: 'Q1 Estimated Tax',
    revenue_annual: 1250000
  },
  {
    id: 'cli_002',
    name: 'Sarah Chen',
    email: 'sarah.chen@example.com',
    entity_type: 'LLC',
    next_deadline: daysAhead(12),
    next_deadline_type: 'S-Corp Election Deadline',
    revenue_annual: 240000
  },
  {
    id: 'cli_003',
    name: 'Elena Martinez',
    email: 'elena.m@example.com',
    entity_type: 'LLC',
    next_deadline: daysAhead(4),
    next_deadline_type: 'Schedule E Filing',
    revenue_annual: 380000
  }
];

// ─── Admin & Collaboration ──────────────────────────────────────────────────

const MOCK_TEAM_MEMBERS = [
  {
    id: 'tm_001',
    name: 'Ebere Okoye',
    email: 'ebere@thewealthbuildingcpa.com',
    phone: '+18885025672',
    role: 'owner',
    title: 'Founder & CPA/MBA',
    status: 'active',
    avatar_color: '#c9a84c',
    bio: 'Founder and lead CPA of The Wealth Building CPA. CPA + MBA with years of tax and financial-planning experience in the Washington Metro area. Personal real estate investor with properties across 5 states.',
    timezone: 'America/New_York',
    pronouns: 'she/her',
    notification_prefs: { email_escalations: true, sms_escalations: true, mentions: true, daily_digest: true },
    last_active_at: minsAgo(4),
    created_at: daysAgo(720)
  },
  {
    id: 'tm_002',
    name: 'Angela Reyes',
    email: 'angela@wbcpa.com',
    phone: '+12025550002',
    role: 'admin',
    title: 'Practice Manager',
    status: 'active',
    avatar_color: '#b0916b',
    bio: 'Runs day-to-day ops, client onboarding, and team coordination.',
    timezone: 'America/New_York',
    pronouns: 'she/her',
    notification_prefs: { email_escalations: true, sms_escalations: true, mentions: true, daily_digest: true },
    last_active_at: minsAgo(22),
    created_at: daysAgo(540)
  },
  {
    id: 'tm_003',
    name: 'Devon Parker',
    email: 'devon@wbcpa.com',
    phone: '+12025550003',
    role: 'manager',
    title: 'Senior Tax Advisor',
    status: 'active',
    avatar_color: '#6d8ac7',
    bio: 'EA. 9 years specializing in S-Corp election strategy and 1031 exchanges.',
    timezone: 'America/New_York',
    pronouns: 'they/them',
    notification_prefs: { email_escalations: true, sms_escalations: false, mentions: true, daily_digest: false },
    last_active_at: hoursAgo(1),
    created_at: daysAgo(380)
  },
  {
    id: 'tm_004',
    name: 'Maya Singh',
    email: 'maya@wbcpa.com',
    phone: '+12025550004',
    role: 'staff',
    title: 'Tax Associate',
    status: 'active',
    avatar_color: '#4ea58a',
    bio: 'CPA candidate. Handles individual returns, estimated taxes, and IRS notice responses.',
    timezone: 'America/New_York',
    pronouns: 'she/her',
    notification_prefs: { email_escalations: true, sms_escalations: false, mentions: true, daily_digest: false },
    last_active_at: minsAgo(12),
    created_at: daysAgo(210)
  },
  {
    id: 'tm_005',
    name: 'Luis Ortega',
    email: 'luis@wbcpa.com',
    phone: '+12025550005',
    role: 'staff',
    title: 'Client Success',
    status: 'active',
    avatar_color: '#4ea58a',
    bio: 'Client onboarding, renewals, and the first line of phone/email support.',
    timezone: 'America/Chicago',
    pronouns: 'he/him',
    notification_prefs: { email_escalations: true, sms_escalations: true, mentions: true, daily_digest: false },
    last_active_at: hoursAgo(3),
    created_at: daysAgo(150)
  },
  {
    id: 'tm_006',
    name: 'Rita Kohl',
    email: 'rita@wbcpa.com',
    phone: '+12025550006',
    role: 'viewer',
    title: 'Bookkeeper (read-only)',
    status: 'active',
    avatar_color: '#7a7f8c',
    bio: 'Reviews monthly bookkeeping and reports. Read-only access only.',
    timezone: 'America/New_York',
    pronouns: 'she/her',
    notification_prefs: { email_escalations: false, sms_escalations: false, mentions: true, daily_digest: true },
    last_active_at: daysAgo(2),
    created_at: daysAgo(90)
  },
  {
    id: 'tm_007',
    name: 'Taylor Finch',
    email: 'taylor@wbcpa.com',
    phone: null,
    role: 'staff',
    title: 'Tax Intern',
    status: 'invited',
    avatar_color: '#4ea58a',
    bio: '',
    timezone: 'America/New_York',
    pronouns: '',
    notification_prefs: { email_escalations: true, sms_escalations: false, mentions: true, daily_digest: false },
    last_active_at: null,
    created_at: daysAgo(3)
  },
  {
    id: 'tm_008',
    name: 'Morgan Leigh',
    email: 'morgan@wbcpa.com',
    phone: '+12025550008',
    role: 'staff',
    title: 'Former Associate',
    status: 'deactivated',
    avatar_color: '#4ea58a',
    bio: '',
    timezone: 'America/New_York',
    pronouns: '',
    notification_prefs: { email_escalations: false, sms_escalations: false, mentions: false, daily_digest: false },
    last_active_at: daysAgo(60),
    created_at: daysAgo(420)
  }
];

const MOCK_ACTIVITY_LOG = [
  { id: 'act_001', actor_id: 'tm_002', actor_name: 'Angela Reyes', action: 'subscriber.updated', target_type: 'subscriber', target_id: 'sub_002', target_label: 'Sarah Chen', summary: 'Raised tier from Standard → Premium', at: minsAgo(8) },
  { id: 'act_002', actor_id: 'tm_004', actor_name: 'Maya Singh', action: 'email.resolved', target_type: 'email', target_id: 'email_003', target_label: 'IRS Notice CP2000', summary: 'Replied to David Ramirez after staff review', at: minsAgo(24) },
  { id: 'act_003', actor_id: 'tm_001', actor_name: 'Ebere Okoye', action: 'agent.deployed', target_type: 'agent', target_id: 'bland_agent', target_label: 'Voice Agent', summary: 'Redeployed with PEAK_SEASON tone', at: hoursAgo(1) },
  { id: 'act_004', actor_id: 'tm_003', actor_name: 'Devon Parker', action: 'task.assigned', target_type: 'task', target_id: 'task_002', target_label: 'Review 1031 replacement list', summary: 'Assigned to Maya Singh', at: hoursAgo(2) },
  { id: 'act_005', actor_id: 'tm_002', actor_name: 'Angela Reyes', action: 'team.invited', target_type: 'team_member', target_id: 'tm_007', target_label: 'Taylor Finch', summary: 'Invited as Staff', at: daysAgo(3) },
  { id: 'act_006', actor_id: 'tm_001', actor_name: 'Ebere Okoye', action: 'role.permission_changed', target_type: 'role', target_id: 'manager', target_label: 'Manager role', summary: 'Granted appointments.cancel', at: daysAgo(5) },
  { id: 'act_007', actor_id: 'tm_005', actor_name: 'Luis Ortega', action: 'note.created', target_type: 'subscriber', target_id: 'sub_001', target_label: 'Marcus Johnson', summary: 'Added internal note re: 1031 timing', at: daysAgo(1) },
  { id: 'act_008', actor_id: 'tm_001', actor_name: 'Ebere Okoye', action: 'system.setting_changed', target_type: 'setting', target_id: 'auto_send_enabled', target_label: 'Auto-send emails', at: daysAgo(2), summary: 'Turned ON' },
  { id: 'act_009', actor_id: 'tm_002', actor_name: 'Angela Reyes', action: 'team.deactivated', target_type: 'team_member', target_id: 'tm_008', target_label: 'Morgan Leigh', summary: 'Offboarded', at: daysAgo(60) },
  { id: 'act_010', actor_id: 'tm_003', actor_name: 'Devon Parker', action: 'appointment.booked', target_type: 'appointment', target_id: 'appt_004', target_label: 'Cost seg review — Elena Martinez', summary: 'Manually booked', at: hoursAgo(2) }
];

const MOCK_TASKS = [
  {
    id: 'task_001',
    title: 'Respond to David Ramirez CP2000 notice',
    description: 'Review IRS CP2000. Pull 1099-K data from Stripe + PayPal for 2023. Draft response by Friday.',
    status: 'in_progress',
    priority: 'high',
    assignee_id: 'tm_003',
    assignee_name: 'Devon Parker',
    creator_id: 'tm_001',
    creator_name: 'Ebere Okoye',
    due_at: daysAhead(2),
    related_type: 'subscriber',
    related_id: 'sub_003',
    related_label: 'David Ramirez',
    created_at: hoursAgo(4),
    updated_at: minsAgo(30),
    comments_count: 3
  },
  {
    id: 'task_002',
    title: 'Review 1031 replacement property shortlist',
    description: 'Marcus is sending 4 candidate properties before Thursday. Confirm each qualifies as like-kind and check 45-day window math.',
    status: 'todo',
    priority: 'high',
    assignee_id: 'tm_004',
    assignee_name: 'Maya Singh',
    creator_id: 'tm_003',
    creator_name: 'Devon Parker',
    due_at: daysAhead(3),
    related_type: 'subscriber',
    related_id: 'sub_001',
    related_label: 'Marcus Johnson',
    created_at: hoursAgo(2),
    updated_at: hoursAgo(2),
    comments_count: 1
  },
  {
    id: 'task_003',
    title: 'Renewal outreach — Robert Kim',
    description: 'Subscription lapsed 35 days ago. Check call history and send personalized renewal email.',
    status: 'todo',
    priority: 'medium',
    assignee_id: 'tm_005',
    assignee_name: 'Luis Ortega',
    creator_id: 'tm_002',
    creator_name: 'Angela Reyes',
    due_at: daysAhead(1),
    related_type: 'subscriber',
    related_id: 'sub_007',
    related_label: 'Robert Kim',
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
    comments_count: 0
  },
  {
    id: 'task_004',
    title: 'Prepare Augusta Rule documentation kit',
    description: 'Draft standard template for Section 280A meeting logs, rental rates, and corporate minutes. Ship as a client-ready PDF.',
    status: 'review',
    priority: 'medium',
    assignee_id: 'tm_004',
    assignee_name: 'Maya Singh',
    creator_id: 'tm_003',
    creator_name: 'Devon Parker',
    due_at: daysAhead(6),
    related_type: null,
    related_id: null,
    related_label: null,
    created_at: daysAgo(4),
    updated_at: hoursAgo(6),
    comments_count: 2
  },
  {
    id: 'task_005',
    title: 'Q1 estimated tax reminder blast',
    description: 'Schedule SMS + email reminders for all active subscribers with Q1 deadline within 10 days.',
    status: 'done',
    priority: 'high',
    assignee_id: 'tm_005',
    assignee_name: 'Luis Ortega',
    creator_id: 'tm_002',
    creator_name: 'Angela Reyes',
    due_at: daysAgo(1),
    related_type: null,
    related_id: null,
    related_label: null,
    created_at: daysAgo(3),
    updated_at: daysAgo(1),
    comments_count: 4
  },
  {
    id: 'task_006',
    title: 'Onboard Taylor Finch',
    description: 'Walk Taylor through agent dashboard, permissions, and escalation protocol. Day-1 checklist.',
    status: 'todo',
    priority: 'low',
    assignee_id: 'tm_002',
    assignee_name: 'Angela Reyes',
    creator_id: 'tm_001',
    creator_name: 'Ebere Okoye',
    due_at: daysAhead(4),
    related_type: 'team_member',
    related_id: 'tm_007',
    related_label: 'Taylor Finch',
    created_at: daysAgo(3),
    updated_at: daysAgo(3),
    comments_count: 0
  }
];

const MOCK_NOTES = [
  {
    id: 'note_001',
    author_id: 'tm_005',
    author_name: 'Luis Ortega',
    target_type: 'subscriber',
    target_id: 'sub_001',
    target_label: 'Marcus Johnson',
    body: 'Heads up: Marcus mentioned a second property sale coming in Q3. Loop Devon in before we lock the 1031 strategy — may want to stack identifications.',
    mentions: ['tm_003'],
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
    pinned: true
  },
  {
    id: 'note_002',
    author_id: 'tm_003',
    author_name: 'Devon Parker',
    target_type: 'subscriber',
    target_id: 'sub_003',
    target_label: 'David Ramirez',
    body: 'Pulled Stripe + PayPal export. Confirmed duplicate reporting on $82,400 of transactions. Drafting response to IRS — will need @Angela Reyes signature before send.',
    mentions: ['tm_002'],
    created_at: hoursAgo(3),
    updated_at: hoursAgo(3),
    pinned: false
  },
  {
    id: 'note_003',
    author_id: 'tm_004',
    author_name: 'Maya Singh',
    target_type: 'subscriber',
    target_id: 'sub_002',
    target_label: 'Sarah Chen',
    body: 'Sarah is right on the fence for S-Corp (benefit ~$6,400/yr after payroll costs). Recommend we explicitly document the cost/benefit in the consult memo so she doesn\'t second-guess in year 2.',
    mentions: [],
    created_at: hoursAgo(8),
    updated_at: hoursAgo(8),
    pinned: false
  },
  {
    id: 'note_004',
    author_id: 'tm_002',
    author_name: 'Angela Reyes',
    target_type: 'call',
    target_id: 'call_003',
    target_label: 'CP2000 escalation call',
    body: 'Transfer recorded cleanly. Client was calm — good. Next time let\'s prep a soft-handoff script for IRS letters so staff pickup feels seamless.',
    mentions: [],
    created_at: daysAgo(2),
    updated_at: daysAgo(2),
    pinned: false
  },
  {
    id: 'note_005',
    author_id: 'tm_001',
    author_name: 'Ebere Okoye',
    target_type: 'general',
    target_id: null,
    target_label: 'Team announcement',
    body: 'Reminder: we are in PEAK_SEASON tone until April 15. Keep call summaries tight — 3 sentences max. Anything complex gets a task, not a long call note.',
    mentions: [],
    created_at: daysAgo(5),
    updated_at: daysAgo(5),
    pinned: true
  }
];

const MOCK_SYSTEM_SETTINGS = {
  auto_send_enabled: true,
  voice_agent_enabled: true,
  inbox_scan_interval_min: 5,
  daily_reminder_hour: 9,
  default_appointment_duration_min: 30,
  require_2fa: false,
  allow_invite_sign_up: true,
  branding: {
    agent_name: 'WBCPA Command Center',
    primary_color: '#c9a84c',
    firm_name: 'WB CPA'
  },
  integrations: {
    supabase:  { connected: false, last_checked: null,          label: 'Database',       required: true  },
    bland_ai:  { connected: false, last_checked: null,          label: 'Voice (Bland AI)', required: true  },
    twilio:    { connected: false, last_checked: null,          label: 'SMS (Twilio)',    required: true  },
    openai:    { connected: false, last_checked: null,          label: 'AI (OpenAI)',     required: true  },
    google:    { connected: false, last_checked: null,          label: 'Calendar + Gmail', required: true  },
    stripe:    { connected: false, last_checked: null,          label: 'Billing (Stripe)', required: false }
  },
  api_keys: [
    { id: 'key_001', label: 'Replit production', last_four: '••••7a2f', created_at: daysAgo(40),  last_used_at: minsAgo(3),   status: 'active' },
    { id: 'key_002', label: 'Bland AI webhook',   last_four: '••••c194', created_at: daysAgo(40),  last_used_at: hoursAgo(2),  status: 'active' },
    { id: 'key_003', label: 'Legacy CI runner',   last_four: '••••09bd', created_at: daysAgo(400), last_used_at: daysAgo(210), status: 'revoked' }
  ]
};

module.exports = {
  MOCK_SUBSCRIBERS,
  MOCK_CALLS,
  MOCK_APPOINTMENTS,
  MOCK_EMAILS,
  MOCK_REVIEW_QUEUE,
  MOCK_CONFIG,
  MOCK_CLIENTS,
  MOCK_TEAM_MEMBERS,
  MOCK_ACTIVITY_LOG,
  MOCK_TASKS,
  MOCK_NOTES,
  MOCK_SYSTEM_SETTINGS
};
